# Overview of NumPy Arrays

Numeric data manipulation in Python is essentially the thing for NumPy array data structure.

We look at examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
The examples shown here may seem a bit dry but they can become very useful in real data science applications.

Some array manipulations covered:

- Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays
- Indexing into arrays: Getting and setting the value of individual array elements
- Slicing of arrays: Getting and setting smaller subarrays within a larger array
- Reshaping of arrays: Changing the shape of a given array
- Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many

## NumPy Array Attributes


Consider these three arrays -  a one-dimensional, two-dimensional, and three-dimensional array.
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [6]:
import numpy as np
np.random.seed(0)  # seed for reproducibility of the random data

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
x4 = np.random.rand(2,3,5) #for a floating point array

#print(x4)

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [7]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

#x1.ndim

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Another useful attribute is the ``dtype``, the data type of the array 

In [11]:
print("dtype:", x3.dtype)

dtype: int64


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [10]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.

In [12]:
# an array of mixed value types
a = np.array([1,2,3.5, "foo"])
print(a.dtype) # U32 - character string
print(a.itemsize) # 128 bytes
print(a.nbytes) # 

<U32
128
512


In [13]:
# what about this?
a = np.array([1,2, 5])
print(a.dtype) # should be float64
print(a.itemsize) # 8 bytes
print(a.nbytes)

int64
8
24


## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [14]:
x1

array([5, 0, 3, 3, 7, 9])

In [28]:
x1[0]

5

In [15]:
x1[4]

7

To index from the end of the array, you can use negative indices:

In [16]:
x1[-1] # similar to a standard List, Tuple, or Dictionary

9

In [17]:
x1[-2]

7

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [18]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [21]:
x2[0, 0]

3

In [22]:
x2[2, 0]

1

In [23]:
x2[2, -1]

7

Values can also be modified using any of the above index notation:

In [24]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. No warning, no runtime error message!

In [25]:
print("x1 before ", x1)
x1[0] = 3.14159  # this will be truncated!
print("x1 after ", x1)

x1 before  [5 0 3 3 7 9]
x1 after  [3 0 3 3 7 9]


In [39]:
# a list will behave differently
t = [9,4,5]
t[0] = 11.5
t

[11.5, 4, 5]

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [26]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x[:5]  # first five elements

array([1, 2, 3, 4])

In [28]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [29]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [30]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [34]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [31]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [47]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [32]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [33]:
x2[:2, :3]  # first two rows, first three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

Array dimensions can even be reversed together:

In [48]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [35]:
print(x2)
print()
print(x2[:, 0])  # first column of x2

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]

[12  7  1]


In [46]:
#print(x2)
#print()
print(x2[0, :])  # first row of x2

[3 5 2 4]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [34]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [36]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Let's extract a $2 \times 2$ subarray from this:

In [37]:
x2_sub = x2[:2, :2] # first two rows, first two columns
print(x2_sub)

[[12  5]
 [ 7  6]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [38]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [52]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [39]:
x2_sub_copy = x2[:2, :2].copy() # use copy function
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [40]:
x2_sub_copy[0, 0] = 42 # will only modify the copy
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [56]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [42]:
grid = np.arange(1, 10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. 


Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [62]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [54]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [55]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [63]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [61]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])# the arrays are passed as a list

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [65]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


It can also be used for two-dimensional arrays:

In [43]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
grid2 = np.array([[7,8,9],
                 [10,11,12]])

In [44]:
# concatenate along the first axis
np.concatenate([grid, grid2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

For working with arrays of mixed dimensions, it is better to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [65]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [48]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

## Array Arithmetic
mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module

In [52]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print()
print(y)
# sum()

[[1. 2.]
 [3. 4.]]

[[5. 6.]
 [7. 8.]]


### Elementwise sum; both produce the array


In [53]:
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)

[[ 6.  8.]
 [10. 12.]]


In [54]:
# using add function of numpy
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


### Elementwise difference; both produce the array


In [55]:
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)


[[-4. -4.]
 [-4. -4.]]


In [56]:

print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


### Elementwise product; both produce the array


In [8]:
# [[ 5.0 12.0]
#  [21.0 32.0]]

print(x * y)


[[ 5. 12.]
 [21. 32.]]


In [9]:
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]


### Elementwise division; both produce the array



In [10]:
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)


[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [11]:
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


### Elementwise square root


In [13]:
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]

print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


### We use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. 
- dot is available both as a function in the numpy module and as an instance method of array objects

In [59]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(x)
print()
print(y)
print()
print(v, w)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[ 9 10] [11 12]


### Inner product of vectors; both produce 219


In [15]:
print(v.dot(w))
print(np.dot(v, w))
# 9x11 + 10x12 = 99+120 = 219

219
219


### Matrix / vector product; both produce the rank 1 array [29 67]


In [17]:
print("First",x.dot(v))
print("Second",np.dot(x, v))

First [29 67]
Second [29 67]


### Matrix / matrix product; both produce the rank 2 array


In [20]:
# [[19 22]
#  [43 50]]
print("A",x.dot(y))
print("B",np.dot(x, y))

A [[19 22]
 [43 50]]
B [[19 22]
 [43 50]]


## numpy sum function on arrays

In [61]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


### Compute sum of all elements; prints "10"

In [22]:
print(np.sum(x))

10


 ### Compute sum of each column; prints "[4 6]"

In [62]:
print(np.sum(x, axis=0)) 

[4 6]


### Compute sum of each row; prints "[3 7]"

In [24]:
print(np.sum(x, axis=1)) 

[3 7]


### A good numpy documentation on array manipulation 
https://numpy.org/doc/stable/reference/routines.array-manipulation.html